/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema;

import Clases.clsConnection;
import Clases.clsFunciones;
import java.io.File;
import java.sql.SQLException;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import static sistema.contanciaSaludCovid.FechaNacimiento;

/**
 *
 * @author USER
 */
public class constanciaTamizajeAntigeno extends javax.swing.JFrame {

   clsConnection oConn = new clsConnection();
    clsFunciones oFunc = new clsFunciones();
    public constanciaTamizajeAntigeno() {
        initComponents();
            setLocationRelativeTo(null);

    }
     

Date fechan;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel118 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        txtNordenIn5 = new javax.swing.JTextField();
        btnEditarIn5 = new javax.swing.JButton();
        jLabel123 = new javax.swing.JLabel();
        FechaExIn5 = new com.toedter.calendar.JDateChooser();
        jTextField15 = new javax.swing.JTextField();
        txtImprimirIn5 = new javax.swing.JTextField();
        btnImprimir5 = new javax.swing.JButton();
        jLabel124 = new javax.swing.JLabel();
        txtNombresIn5 = new javax.swing.JTextField();
        txtEdadIn5 = new javax.swing.JTextField();
        txtDniIn5 = new javax.swing.JTextField();
        jLabel125 = new javax.swing.JLabel();
        jLabel126 = new javax.swing.JLabel();
        jLabel127 = new javax.swing.JLabel();
        jLabel128 = new javax.swing.JLabel();
        txtLaempresa = new javax.swing.JTextField();
        jLabel129 = new javax.swing.JLabel();
        jLabel130 = new javax.swing.JLabel();
        jLabel131 = new javax.swing.JLabel();
        jLabel132 = new javax.swing.JLabel();
        btnGrabarIn4 = new javax.swing.JButton();
        btnLimpiarIn4 = new javax.swing.JButton();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel118.setBackground(new java.awt.Color(153, 255, 153));
        jLabel118.setFont(new java.awt.Font("Engravers MT", 3, 18)); // NOI18N
        jLabel118.setForeground(new java.awt.Color(102, 0, 0));
        jLabel118.setText("CONSTANCIA MEDICA DE TAMIZAJE - COVID 19");

        jLabel116.setText("Nº Orden :");

        txtNordenIn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNordenIn5ActionPerformed(evt);
            }
        });
        txtNordenIn5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNordenIn5KeyTyped(evt);
            }
        });

        btnEditarIn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/configuracion.png"))); // NOI18N
        btnEditarIn5.setText("Editar");
        btnEditarIn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarIn5ActionPerformed(evt);
            }
        });

        jLabel123.setText("Fecha :");

        FechaExIn5.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                FechaExIn5PropertyChange(evt);
            }
        });

        jTextField15.setBackground(new java.awt.Color(255, 204, 153));
        jTextField15.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jTextField15.setForeground(new java.awt.Color(0, 0, 51));
        jTextField15.setText("Imprimir");

        txtImprimirIn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImprimirIn5ActionPerformed(evt);
            }
        });

        btnImprimir5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/impresora.png"))); // NOI18N
        btnImprimir5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimir5ActionPerformed(evt);
            }
        });

        jLabel124.setText("de :");

        txtEdadIn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadIn5ActionPerformed(evt);
            }
        });

        jLabel125.setText("identificado con DNI;");

        jLabel126.setText("años de edad,");

        jLabel127.setText("Conste por la presente que el SR:");

        jLabel128.setText("colaborador de la empresa ");

        jLabel129.setText("no tiene sintomatologia ni sintomas relacionados con covid-19, al momento de la evaluacion. Así mismo se deja constancia");

        jLabel130.setText("que en la misma fecha de evaluación médica se la realizó la prueba de ANTIGENOS VIRALES SARS-COV2, para la detección");

        jLabel131.setText("del corona virus causante  de la enfermedad COVID-19, cuyo resultado es :");

        jLabel132.setText("Se suscribe constancia médica para fines pertinentes.");

        btnGrabarIn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add.png"))); // NOI18N
        btnGrabarIn4.setText("Grabar/Actualizar");
        btnGrabarIn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarIn4ActionPerformed(evt);
            }
        });

        btnLimpiarIn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar.png"))); // NOI18N
        btnLimpiarIn4.setText("Limpiar");
        btnLimpiarIn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarIn4ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("SINTOMATICO");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setText("ASINTOMATICO");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox1.setText("ANTICUERPOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel123)
                        .addGap(18, 18, 18)
                        .addComponent(FechaExIn5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox3)
                            .addComponent(jCheckBox2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGrabarIn4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpiarIn4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtImprimirIn5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnImprimir5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel118))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel116)
                                .addGap(18, 18, 18)
                                .addComponent(txtNordenIn5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditarIn5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel127)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombresIn5, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel124)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEdadIn5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel126))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel125)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDniIn5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel128)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtLaempresa, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel129, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                            .addComponent(jLabel130, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel131, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel132, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(143, 143, 143)))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel118)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel116)
                    .addComponent(txtNordenIn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarIn5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel127)
                    .addComponent(txtNombresIn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel124)
                    .addComponent(txtEdadIn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel126))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel125)
                    .addComponent(txtDniIn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel128)
                    .addComponent(txtLaempresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jLabel129)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel130)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel131)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel132, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FechaExIn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel123))
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox2)
                            .addComponent(jCheckBox1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGrabarIn4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimpiarIn4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtImprimirIn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnImprimir5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
void Fecha1(){
Date fechaDate = new Date();
//SimpleDateFormat formateador = new SimpleDateFormat("'HUAMACHUCO - ' EEEEE dd MMMMM yyyy");
FechaExIn5.setDate(fechaDate);
}

 public boolean OrdenExisteIn4()
     {
        boolean bResultado=false;
        if(!txtNordenIn5.getText().isEmpty()){
        String sQuery;
        sQuery  = "Select n_orden from constanciaTamizajeCovid Where n_orden ="+txtNordenIn5.getText().toString();
        oConn.FnBoolQueryExecute(sQuery);
        try {
            if (oConn.setResult.next())
            {
                bResultado = true;
//             oFunc.SubSistemaMensajeError("Número de Orden Utilizado");
//             txtNorden.setText(null);
            }
            oConn.setResult.close();
        } catch (SQLException ex) {
        }
        }       
        return bResultado;
     }

    private void txtNordenIn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNordenIn5ActionPerformed
       FechaNacimiento = new com.toedter.calendar.JDateChooser();
        if(!txtNordenIn5.getText().isEmpty()){
            if(!OrdenExisteIn4()){
                String Sql="SELECT d.cod_pa, d.nombres_pa||' '||d.apellidos_pa as nombre, d.fecha_nacimiento_pa ,"
                + "d.sexo_pa,n.tipoprueba,n.razon_empresa, n.cargo_de "
                + "FROM datos_paciente AS d "
                + "INNER JOIN n_orden_ocupacional AS n ON (d.cod_pa = n.cod_pa) "
                + "WHERE n.n_orden ='"+txtNordenIn5.getText() +"'";
                oConn.FnBoolQueryExecute(Sql);
                try {
                    if (oConn.setResult.next()) {
                        txtNombresIn5.setText(oConn.setResult.getString("nombre"));
                        txtDniIn5.setText(oConn.setResult.getString("cod_pa"));
                   //    fechan.setDate(oConn.setResult.getDate("fecha_nacimiento_pa"));
                       FechaNacimiento.setDate(oConn.setResult.getDate("fecha_nacimiento_pa"));
                       System.out.println("la fecha:"+String.valueOf(oFunc.calcularEdad(FechaNacimiento.getCalendar())));
                       txtEdadIn5.setText(String.valueOf(oFunc.calcularEdad(FechaNacimiento.getCalendar())) );

                       // txtLaboral.setText(oConn.setResult.getString("cargo_de"));
                      //  txtLaboral.setText(oConn.setResult.getString("cargo_de"));
                        txtLaempresa.setText(oConn.setResult.getString("razon_empresa"));
                        txtNordenIn5.setEditable(false);
                        Fecha1();
                        // FechaHoy.requestFocusInWindow();
                     //   oPe.fecha(FechaExIn4);
                        //   oPe.fecha(FechaHotel);

                    }else{
                        oFunc.SubSistemaMensajeError("No se encuentra Algunos Registros necesarios(Alta en Ex-Ocupacionales)");
                    }
                    oConn.setResult.close();
                } catch (SQLException ex) {
                    oFunc.SubSistemaMensajeInformacion("Inmunologia:" + ex.getMessage().toString());}
            }else{
                oFunc.SubSistemaMensajeError("No se encuentra Algunos Registros necesarios");
            }
        }
    }//GEN-LAST:event_txtNordenIn5ActionPerformed

    private void txtNordenIn5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNordenIn5KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNordenIn5KeyTyped

    private void btnEditarIn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarIn5ActionPerformed
        FechaNacimiento = new com.toedter.calendar.JDateChooser();
           if(!txtNordenIn5.getText().isEmpty()){
            String Sql=" SELECT d.cod_pa, d.nombres_pa||' '||d.apellidos_pa as nombre, d.fecha_nacimiento_pa,n.razon_empresa,\n" +
                                " n.cargo_de, ci.fecha,ci.sintomatico,ci.asintomatico \n" +
"                            FROM datos_paciente AS d   \n" +
"                            INNER JOIN n_orden_ocupacional AS n ON (d.cod_pa = n.cod_pa) \n" +
"                            left JOIN constanciaTamizajeCovid AS ci ON (ci.n_orden = n.n_orden) \n" +
"                            WHERE n.n_orden ="+txtNordenIn5.getText();
            oConn.FnBoolQueryExecute(Sql);
            try {
                if (oConn.setResult.next()) {
                    txtNombresIn5.setText(oConn.setResult.getString("nombre"));
                    txtDniIn5.setText(oConn.setResult.getString("cod_pa"));
                    jCheckBox2.setSelected(oConn.setResult.getBoolean("sintomatico"));
                     jCheckBox3.setSelected(oConn.setResult.getBoolean("asintomatico"));

                 //   txtEdadIn4.setText(String.valueOf(oFunc.calcularEdad(FechaNacimiento.getCalendar())) );
                    FechaExIn5.setDate(oConn.setResult.getDate("fecha"));
                    txtLaempresa.setText(oConn.setResult.getString("razon_empresa"));
                }else{
                    oFunc.SubSistemaMensajeError("No se encuentra Algunos Registros necesarios");
                }
                oConn.setResult.close();
            } catch (SQLException ex) {
                oFunc.SubSistemaMensajeInformacion("Ficha inmunologica:" + ex.getMessage().toString());}
        }
    }//GEN-LAST:event_btnEditarIn5ActionPerformed

    private void FechaExIn5PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_FechaExIn5PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_FechaExIn5PropertyChange

    private void txtImprimirIn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImprimirIn5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImprimirIn5ActionPerformed

    private void btnImprimir5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimir5ActionPerformed
       if(jCheckBox1.isSelected())
       {
        if(!txtImprimirIn5.getText().isEmpty()){
            //System.out.println("el valor de imprimit es:"+txtImprimirIn1.getText());
            printIn6(Integer.valueOf(txtImprimirIn5.getText()));
        }
       }
        else
       {if(!txtImprimirIn5.getText().isEmpty()){
            //System.out.println("el valor de imprimit es:"+txtImprimirIn1.getText());
            printIn4(Integer.valueOf(txtImprimirIn5.getText()));
          }
       }
    }//GEN-LAST:event_btnImprimir5ActionPerformed

    private void btnGrabarIn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarIn4ActionPerformed

        if(OrdenExisteIn4()){
            ActualizarIn4();
            limpiar4();

        }
        else{
            if(!txtNordenIn5.getText().isEmpty()){
                try {
                    if(validarIn4()){
                        if(GrabarIn4()){
                            if(jCheckBox1.isSelected())
       {System.out.println("entro a grabar ");
       
            printIn5(Integer.valueOf(txtNordenIn5.getText().toString()));
        
       }
        else
        imprimirIn4();
                            limpiar4();
                        }
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(constanciaTamizajeAntigeno.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btnGrabarIn4ActionPerformed
     private void printIn4(Integer cod){

                Map parameters = new HashMap(); 
                parameters.put("Norden",cod);             
                
                  try 
                {
                    String direccionReporte = System.getProperty("user.dir")+File.separator+"reportes"+File.separator+"contanciatamizajeAntigeno.jasper";
                    JasperReport myReport = (JasperReport) JRLoader.loadObjectFromFile(direccionReporte);
                    JasperPrint myPrint = JasperFillManager.fillReport(myReport,parameters,clsConnection.oConnection);
                    JasperViewer viewer = new JasperViewer(myPrint, false);
                    viewer.setTitle("CONSENTIMIENTO INFORMADO");
                   // viewer.setAlwaysOnTop(true);
                    viewer.setVisible(true);
                 } catch (JRException ex) {
                    Logger.getLogger(constanciaTamizajeAntigeno.class.getName()).log(Level.SEVERE, null, ex);
                }
 } 
       private void printIn6(Integer cod){
                System.out.println("imprmir 5");
                Map parameters = new HashMap(); 
                parameters.put("Norden",cod);             
                System.out.println("imprmir 5");
                  try 
                {  
                  
                    String direccionReporte = System.getProperty("user.dir")+File.separator+"reportes"+File.separator+"contanciatamizajeAnticuerpos.jasper";
                    JasperReport myReport = (JasperReport) JRLoader.loadObjectFromFile(direccionReporte);
              JasperPrint myPrint = JasperFillManager.fillReport(myReport,parameters,clsConnection.oConnection);
                    JasperViewer viewer = new JasperViewer(myPrint, false);
                    viewer.setTitle("CONSENTIMIENTO INFORMADO");
                   // viewer.setAlwaysOnTop(true);
                    viewer.setVisible(true);
                 } catch (JRException ex) {
                    Logger.getLogger(constanciaTamizajeAntigeno.class.getName()).log(Level.SEVERE, null, ex);
                }
 } 
     
     
     
     private void printIn5(Integer cod){
                System.out.println("imprmir 5");
                Map parameters = new HashMap(); 
                parameters.put("Norden",cod);             
                System.out.println("imprmir 5");
                  try 
                {  
                  
                    String direccionReporte = System.getProperty("user.dir")+File.separator+"reportes"+File.separator+"contanciatamizajeAnticuerpos.jasper";
                    JasperReport myReport = (JasperReport) JRLoader.loadObjectFromFile(direccionReporte);
                  JasperPrint jasperPrint= JasperFillManager.fillReport(myReport,parameters,clsConnection.oConnection);
                    
                  JasperPrintManager.printReport(jasperPrint,true);
                 } catch (JRException ex) {
                    Logger.getLogger(constanciaTamizajeAntigeno.class.getName()).log(Level.SEVERE, null, ex);
                }
 } 
     
     
     
     public void ActualizarIn4(){
            String sCodigo=txtNordenIn5.getText();
            String strSqlStmt;

            strSqlStmt="UPDATE constanciaTamizajeCovid\n" +
                    " SET fecha='"+FechaExIn5.getDate()
                    +"', sintomatico='"+jCheckBox2.isSelected()+"',"
                     +" asintomatico='"+jCheckBox3.isSelected()+"'"

                 +  "  WHERE n_orden='"+sCodigo+"';";
                 System.out.println(strSqlStmt);
            //oFunc.SubSistemaMensajeInformacion(strSqlStmt);
            if (oConn.FnBoolQueryExecuteUpdate(strSqlStmt)) {
                oFunc.SubSistemaMensajeInformacion("Se ha actualizado la Entrada con Éxito");
                if(jCheckBox1.isSelected()){
                    printIn5(Integer.valueOf(txtNordenIn5.getText().toString()));
                }
                else{
                    imprimirIn4();
                    limpiar4();
                }
                try {
                    oConn.setResult.close();
                } catch (SQLException ex) {
                    Logger.getLogger(constanciaTamizajeAntigeno.class.getName()).log(Level.SEVERE, null, ex);
                }
            } 
            else {
                oFunc.SubSistemaMensajeError("No se pudo Agregar La Entrada");
            }
    }
       private boolean imprimirIn4(){
        boolean im = false;
        int seleccion = JOptionPane.showOptionDialog(
            this, // Componente padre
            "¿Desea Imprimir?", //Mensaje
            "Seleccione una opción", // Título
            JOptionPane.YES_NO_CANCEL_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,    // null para icono por defecto.
            new Object[] { "Si", "No"},    // null para YES, NO y CANCEL
            "Si");
            if (seleccion != -1)
            {
           if((seleccion + 1)==1)
           {
              printerIn4(Integer.valueOf(txtNordenIn5.getText()));
               im = true;
           }
           else
           {
              // PRESIONO NO
             }
            }
            return im;

        }
        private void printerIn4(Integer cod){
                 Map parameters = new HashMap(); 
                parameters.put("Norden",cod);      
                    try 
                {                     
                    String direccionReporte = System.getProperty("user.dir")+File.separator+"reportes"+File.separator+"contanciatamizajeAntigeno.jasper";
                    JasperReport myReport = (JasperReport) JRLoader.loadObjectFromFile(direccionReporte);
                    JasperPrint jasperPrint= JasperFillManager.fillReport(myReport,parameters,clsConnection.oConnection);
                    
                  JasperPrintManager.printReport(jasperPrint,true);
                  
                   } catch (JRException ex) {
                    Logger.getLogger(Odontograma.class.getName()).log(Level.SEVERE, null, ex);
                }
   } 
       
    private boolean GrabarIn4() throws SQLException{
        boolean bResult = false;
        String strSqlStmt = "insert into constanciaTamizajeCovid ";       
            strSqlStmt+= "values("+ txtNordenIn5.getText()+",'"+FechaExIn5.getDate().toString()+
                    "','"+jCheckBox2.isSelected()+"','"+jCheckBox3.isSelected()+"')";
            System.out.println(strSqlStmt);
//        oFunc.SubSistemaMensajeError(strSqlStmt);
             if (oConn.FnBoolQueryExecuteUpdate(strSqlStmt)){
//                   oConn.setResult.next();
                    oFunc.SubSistemaMensajeInformacion("Examen Registrada");
                    
                   bResult = true;
                   try {
                    oConn.setResult.close();
                } catch (SQLException ex) {
                    Logger.getLogger(constanciaTamizajeAntigeno.class.getName()).log(Level.SEVERE, null, ex);
                }
               }
                return bResult;       
        }
      
    
    
    private boolean validarIn4(){
        boolean bResultado=true;

            if (((JTextField)FechaExIn5.getDateEditor().getUiComponent()).getText().trim().length()< 2 ) 
                {oFunc.SubSistemaMensajeError("Ingrese Fecha ");bResultado = false;}

           return bResultado;
} 
    private void btnLimpiarIn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarIn4ActionPerformed
        limpiar4();
    }//GEN-LAST:event_btnLimpiarIn4ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        if(jCheckBox2.isSelected())
        jCheckBox3.setSelected(false);
        else
        jCheckBox3.setSelected(true);
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        if(jCheckBox3.isEnabled())
        jCheckBox2.setSelected(false);
        else
        jCheckBox2.setSelected(true);
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void txtEdadIn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadIn5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadIn5ActionPerformed
  public void limpiar4(){
      txtNordenIn5.setText("");
        txtNombresIn5.setText("");
                    txtDniIn5.setText("");
      FechaExIn5.setDate(null);
                    txtLaempresa.setText("");
    txtNordenIn5.setEditable(true);
    jCheckBox2.setSelected(false);
                jCheckBox3.setSelected(false);

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(constanciaTamizajeAntigeno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(constanciaTamizajeAntigeno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(constanciaTamizajeAntigeno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(constanciaTamizajeAntigeno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new constanciaTamizajeAntigeno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser FechaExIn5;
    private javax.swing.JButton btnEditarIn5;
    private javax.swing.JButton btnGrabarIn4;
    private javax.swing.JButton btnImprimir5;
    private javax.swing.JButton btnLimpiarIn4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField txtDniIn5;
    private javax.swing.JTextField txtEdadIn5;
    private javax.swing.JTextField txtImprimirIn5;
    private javax.swing.JTextField txtLaempresa;
    private javax.swing.JTextField txtNombresIn5;
    private javax.swing.JTextField txtNordenIn5;
    // End of variables declaration//GEN-END:variables
}
